### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hacker1024** [Ninlives/deckbd#1]
Hi,
What is the license for this software?

**Comment by Ninlives** [comment]
I haven't decided yet because I'm not very familiar with various open-source licenses. However, I would very much welcome Jovian-Nixos to use this project. In this case, which type of license would you recommend?

**Comment by hacker1024** [comment]
GitHub have a [website](https://choosealicense.com) to help you choose if you'd like to compare and contrast. Personally, I usually go with MIT or GPL, depending on whether I want to allow usage in closed-source projects or not. For something like this, I'd probably do MIT, which is quite permissive.

**Comment by hacker1024** [comment]
Thanks!
